/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_rdma_RdmaChannel */

#ifndef _Included_io_rdma_RdmaChannel
#define _Included_io_rdma_RdmaChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_rdma_RdmaChannel
 * Method:    init
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_io_rdma_RdmaChannel_init
    (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     io_rdma_RdmaChannel
 * Method:    sendHeader
 * Signature: (Ljava/lang/String;ILjava/nio/ByteBuffer;ILio/rdma/RdmaSendCallback;)V
 */
JNIEXPORT void JNICALL Java_io_rdma_RdmaChannel_sendHeader
    (JNIEnv *, jobject, jstring, jint, jobject, jint, jobject);

/*
 * Class:     io_rdma_RdmaChannel
 * Method:    sendHeaderWithBody
 * Signature: (Ljava/lang/String;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;JLio/rdma/RdmaSendCallback;)V
 */
JNIEXPORT void JNICALL Java_io_rdma_RdmaChannel_sendHeaderWithBody
    (JNIEnv *, jobject, jstring, jint, jobject, jint, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif